### ISSUE TITLE
Make Create/Update commands for Car

### ISSUE THREAD

**Issue by iliantrifonov** [nikitrifonovprojects/Datebase-Access#29]
The create/edit model should have all fields that you need to create a valid car. This means it should have the possibility of any of the properties to be filled. (example https://www.mobile.bg/pcgi/mobile.cgi?pubtype=1&act=2). For example they may add extras, door types, car makes etc to that model. Place appropriate validation (some fields will not be required).

**Comment by nikitrifonovprojects** [comment]
Id's greater than zero

**Comment by iliantrifonov** [comment]
Bug on #34 also affects this.
